config/routes.rb
Rails.application.routes.draw do
  get 'search' => 'search#index'
  devise_for :users
  get 'index/index'
	root to: 'index#index'
	resources :users
	resources :posts, except: %i[edit update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hash_tag.rb
class HashTag < ApplicationRecord
	has_many :post_hash_tags
	has_many :posts, through: :post_hash_tags
end

app/models/post.rb
class Post < ApplicationRecord
  after_commit :create_tags, on: :create
  belongs_to :user
  has_many :post_hash_tags
  has_many :hash_tags, through: :post_hash_tags
  has_one_attached :image


  validate :image_presence

  def image_presence
    errors.add(:image, "Can't be blank. Please upload an image") unless image.attached?
  end

  def create_tags
    extract_hashtags_from_post.each do |tag|
      hash_tags.create(name: tag)
    end
  end

  private

  def extract_hashtags_from_post
    description.to_s.scan(/#\w+/).map{ |word| word.gsub("#", "") }
  end
end

app/models/post_hash_tag.rb
class PostHashTag < ApplicationRecord
  belongs_to :post
  belongs_to :hash_tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index; end

	def new; end

	def create
		Post.create(post_params)
		redirect_to root_path
	end

	def show
		@post = Post.find(params[:id])
		@user_post = current_user.posts.find_by!(id: params[:id])
		rescue ActiveRecord::RecordNotFound
	end

	def destroy
		post = current_user.posts.find(params[:id])
		post.destroy

		redirect_to root_path
	end

	private

	def post_params
		params.require(:post).permit(:description, :image, :user_id)
	end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:query].start_with?("#")
      query = params[:query].gsub("#", "")
      @posts = Post.joins(:hash_tags).where(hash_tags: {
          name: query
      })
    else
      @posts = Post.where("lower(description) like lower(?)", "%#{params[:query]}%")
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit]
  def show
    @posts = @user.posts.order(created_at: :desc)
  end

  def edit
    @posts = @user.posts.order(created_at: :desc)
  end

  def update
    current_user.update(user_params)
	  redirect_to current_user
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :username, :website, :bio, :phone, :gender, :email, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/index/index.html.erb
<div class="posts">
  <% @posts.map do |post| %>
    <section class="post">
      <div class="user">
        <div class="avatar">
          <% if post.user.avatar.attached? %>
            <%= link_to user_path(post.user) do %>
              <%= image_tag post.user.avatar %>
            <% end %>
          <% end %>
        </div>
        <%= link_to post.user.username, user_path(post.user), class: "username" %>
      </div>
      <%= link_to post_path(post) do %>
        <%= image_tag post.image, class: 'main-image' %>
      <% end %>
      <div class="description">
        <%= link_to post_path(post), class: "post-description" do %>
          <% post.description.to_s.split(" ").each do |word| %>
            <% if word.start_with?("#") %>
              <%= link_to word, search_path(query: word) %>
            <% else %>
              <%= word %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </section>
  <% end %>
  <%= paginate @posts %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Magarats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--Navigation Bar-->
    <nav class="navbar navbar-light bg-light d-flex">
      <div class="container">
        <div class="logo">
          <%= link_to root_path, class: "navbar-brand" do %>
            <%= fa_stacked_icon "camera inverse", base: "circle"%>
            Magarat
          <% end %>
        </div>
        <div class="m-auto">
          <%= form_with url: search_path, method: :get, local: true, class: "form-inline search-form" do |form| %>
            <%= form.text_field :query, value: params[:query], class: "form-control mr-sm-2",
              placeholder: "#search"
            %>
          <% end %>
        </div>
        <div class="user-section">
          <a href="<%= destroy_user_session_path %>" data-method="delete"><i class="fa fa-compass"></i></a>
          <a><i class="fa fa-heart"></i></a>
          <% if user_signed_in? %>
            <a href="<%= user_path(current_user) %>"><i class="fa fa-user"></i></a>
          <% else %>
            <a href="<%= new_user_session_path %>"><i class="fa fa-sign-in"></i></a>
          <% end %>
        </div>
      </div>
    </nav>

    <!--Main content-->
    <main class="container" style="min-height: 500px;">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </main>

    <!--Footer-->
    <footer class="container footer">
      <nav class="navbar d-flex">
        <ul>
          <li>ABOUT US
          </li>
          <li>SUPPORT</li>
          <li>PRESS</li>
          <li>API</li>
          <li>JOBS</li>
          <li>PRIVACY</li>
          <li>TERMS</li>
          <li>DIRECTORY</li>
          <li>PROFILES</li>
          <li>HASHTAGS</li>
          <li>LANGUAGE</li>
        </ul>
        <p> © 2019 MAGARAT </p>
      </nav>
    </footer>
  </body>
</html>

app/views/posts/new.html.erb
<%= form_with model: Post.new, class: "form-upload" do |f| %>
  <div class="form-group">
    <%= f.text_field :description %>
  </div>
  <div class="form-group">
    <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <%= f.text_field :user_id, value: current_user.id, class:'d-none'%>
  </div>
  <br>
  <div class="text-center">
    <%= f.submit 'Create Post', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="post-show row">
  <div class="col-md-8">
    <%=image_tag @post.image, class: 'image' %>
  </div>
  <div class="col-md-4">
    <div class="user">
      <div class="avatar">
        <% if @post.user.avatar.attached? %>
          <%= link_to user_path(@post.user) do %>
            <%= image_tag @post.user.avatar %>
          <% end %>
        <% end %>
      </div>
      <%= link_to @post.user.username, user_path(@post.user), class: 'username' %>
    </div>
    <div class="description">
      <%= @post.description %>
      <div class="delete-post">
        <% if @user_post %>
          <%= link_to post_path(@user_post), method: :delete, data: { confirm: 'Are you sure' } do %>
            <%= fa_stacked_icon "trash" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/search/index.html.erb
<div class="search-page">
  <% if @posts.exists? %>
    <h1>Top Posts</h1>
  <% else %>
    <h1>Oop! No matching posts ...</h1>
  <% end %>
  <div class="user-images">
    <% @posts.each do |post|%>
      <div class="wrapper">
        <%= link_to post_path(post) do %>
          <%=image_tag post.image %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="user-edit-page">
  <div class="actions">
    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" data-toggle="pill" href="#v-pills-home" role="tab" aria-selected="true">Edit Profile</a>
      <a class="nav-link" data-toggle="pill">Change Password</a>
      <a class="nav-link" data-toggle="pill">Authorized Applications</a>
      <a class="nav-link" data-toggle="pill">Email and SMS</a>
      <a class="nav-link" data-toggle="pill">Manage Contacts</a>
      <a class="nav-link" data-toggle="pill">Privacy and Security</a>
    </div>
  </div>
  <div class="details tab-content">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
      <!-- Form edit profile -->
      <%= form_with model: current_user, local: true, class: "form-horizontal form-edit-user" do |f| %>
        <div class="form-group row">
          <div class="col-sm-3 col-form-label">
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar, class: "avatar" %>
            <% end %>
          </div>
          <div class="col-sm-9">
            <p class="username"><%= current_user.username %></p>
            <a class="change-photo" href="">Change Profile Photo</a>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :avatar, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.file_field :avatar, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :name, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :username, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :username, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :website, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :website, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :bio, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_area :bio, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :email, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :email, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :phone, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :phone, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :gender, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :gender, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-3">
          </div>
          <div class="col-sm-9">
            <%= f.submit "Submit", class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar %>
        <% end %>
      </div>
    </div>

    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%= @user.username %></h2>
        <% if current_user == @user %>
          <a href="<%= edit_user_path(current_user) %>" class="edit-profile">
            <button>Edit Profile</button>
          </a>
        <% end %>
      </div>
      <ul class="posts">
        <li><span><%= @posts.count %></span> posts</li>
        <li><span>195</span> followers</li>
        <li><span>345</span> following</li>
      </ul>
      <h2 class="name"><%= @user.name %></h2>
      <%= link_to @user.website, @user.website, class: "website" %>
    </div>
  </div>

  <div class="user-tabs">
    <a class="tab active" href="">
      <i class="fa fa-th"></i>
      POSTS
    </a>
    <a class="tab" href="">
      <i class="fa fa-tv"></i>
      IGTV
    </a>
    <a class="tab" href="">
      <i class="fa fa-bookmark"></i>
      SAVED
    </a>
    <a class="tab" href="">
      <i class="fa fa-tag"></i>
      TAGGED
    </a>
  </div>

  <div class="user-images">
    <% @posts.map do |post| %>
      <div class="wrapper">
        <%= link_to post_path(post) do %>
          <%= image_tag post.image %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>